[build]
  functions = "netlify/functions"
  publish = "dist"
  node_version = "18.12.0"  # Node.js sürümünü güncelleyin

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  included_files = ["netlify/functions/files/**"]
